<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <RuntimeIdentifier Condition="'$(Platform)' == 'x64'">win-x64</RuntimeIdentifier>
    <RuntimeIdentifier Condition="'$(Platform)' == 'ARM64'">win-arm64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>

    <BaseOutputPath>$(MSBuildThisFileDirectory)..\artifacts\tests\</BaseOutputPath>

  </PropertyGroup>

  <ItemGroup>
    <None Remove="Core\Logger.PrivateDump.expected.txt" />
    <None Remove="Core\Logger.PrivateDump.original.txt" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Core\Logger.PrivateDump.expected.txt" />
    <EmbeddedResource Include="Core\Logger.PrivateDump.original.txt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\App\MouseWithoutBorders.Standalone.csproj" />
  </ItemGroup>

</Project>
