<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <RuntimeIdentifier Condition="'$(Platform)' == 'x64'">win-x64</RuntimeIdentifier>
    <RuntimeIdentifier Condition="'$(Platform)' == 'ARM64'">win-arm64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>

    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>MouseWithoutBordersHelper</AssemblyName>
    <RootNamespace>MouseWithoutBorders</RootNamespace>
    <DisableWinExeOutputInference>true</DisableWinExeOutputInference>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationIcon>..\ClassicGreen.ico</ApplicationIcon>
    <NoWin32Manifest>true</NoWin32Manifest>
    <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>

    <BaseOutputPath>$(MSBuildThisFileDirectory)..\..\artifacts\standalone\</BaseOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DefineConstants>MM_HELPER;TRACE;DEBUG;STANDALONE;SHOW_ON_WINLOGON;CODE_ANALYSIS;CUSTOMIZE_LOGON_SCREEN</DefineConstants>
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DefineConstants>MM_HELPER;TRACE;STANDALONE;SHOW_ON_WINLOGON;CODE_ANALYSIS;CUSTOMIZE_LOGON_SCREEN</DefineConstants>
    <DebugType>pdbonly</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Class\IClipboardHelper.cs" Link="IClipboardHelper.cs" />
    <Compile Include="..\Core\IpcChannelHelper.cs" Link="IpcChannelHelper.cs" />
    <Compile Include="..\Core\GpoCompatibility.cs" Link="GpoCompatibility.cs" />
    <Compile Include="..\Core\PowerToysRuntimeCompatibility.cs" Link="PowerToysRuntimeCompatibility.cs" />
    <Compile Include="..\Standalone\StandaloneProduct.cs" Link="StandaloneProduct.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" />
    <PackageReference Include="Microsoft.Windows.Compatibility" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="StreamJsonRpc" />
  </ItemGroup>
</Project>
